name: Staging deploy
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  build:
    name: Build and deploy
    runs-on: ubu
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /var/www/board.lesnygacek.pl/html/lesnygacek_strapi
          git fetch --all
          git reset --hard origin/main
          su -
          cd /var/www/board.lesnygacek.pl/html/lesnygacek_strapi
          ${{ secrets.APASS }}
          NODE_ENV=production npm run build
          su ${{ secrets.USERNAME }}
          cd /var/www
          pm2 restart lesnygacek
