name: Staging deploy
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /var/www/board.lesnygacek.pl/html/lesnygacek_strapi
            git fetch --all
            git reset --hard origin/main
            NODE_ENV=production npm run build
            cd /var/www
            pm2 restart lesnygacek
