name: Staging deploy
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/board.lesnygacek.pl/html/lesnygacek_strapi
            git fetch --all
            git reset --hard origin/main
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install --lts
            npm run build
            cd /var/www
            ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/pm2" "/usr/local/bin/pm2"
            pm2 restart lesnygacek
